
package com.mindbodyonline.clients.api._0_5Staff;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Staff_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StaffX0020ServiceSoap {


    /**
     * Gets a list of staff members.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Staff.GetStaffResult
     */
    @WebMethod(operationName = "GetStaff", action = "http://clients.mindbodyonline.com/api/0_5/GetStaff")
    @WebResult(name = "GetStaffResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetStaff", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.GetStaff")
    @ResponseWrapper(localName = "GetStaffResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.GetStaffResponse")
    public GetStaffResult getStaff(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetStaffRequest request);

    /**
     * Gets a list of staff permissions based on the given staff member.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Staff.GetStaffPermissionsResult
     */
    @WebMethod(operationName = "GetStaffPermissions", action = "http://clients.mindbodyonline.com/api/0_5/GetStaffPermissions")
    @WebResult(name = "GetStaffPermissionsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetStaffPermissions", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.GetStaffPermissions")
    @ResponseWrapper(localName = "GetStaffPermissionsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.GetStaffPermissionsResponse")
    public GetStaffPermissionsResult getStaffPermissions(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetStaffPermissionsRequest request);

    /**
     * Add or update staff.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Staff.AddOrUpdateStaffResult
     */
    @WebMethod(operationName = "AddOrUpdateStaff", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateStaff")
    @WebResult(name = "AddOrUpdateStaffResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddOrUpdateStaff", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.AddOrUpdateStaff")
    @ResponseWrapper(localName = "AddOrUpdateStaffResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.AddOrUpdateStaffResponse")
    public AddOrUpdateStaffResult addOrUpdateStaff(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateStaffRequest request);

    /**
     * Gets a staff member's image URL if it exists.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Staff.GetStaffImgURLResult
     */
    @WebMethod(operationName = "GetStaffImgURL", action = "http://clients.mindbodyonline.com/api/0_5/GetStaffImgURL")
    @WebResult(name = "GetStaffImgURLResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetStaffImgURL", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.GetStaffImgURL")
    @ResponseWrapper(localName = "GetStaffImgURLResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.GetStaffImgURLResponse")
    public GetStaffImgURLResult getStaffImgURL(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetStaffImgURLRequest request);

    /**
     * Validates a username and password. This method returns the staff on success.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Staff.ValidateLoginResult
     */
    @WebMethod(operationName = "ValidateStaffLogin", action = "http://clients.mindbodyonline.com/api/0_5/ValidateStaffLogin")
    @WebResult(name = "ValidateStaffLoginResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "ValidateStaffLogin", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.ValidateStaffLogin")
    @ResponseWrapper(localName = "ValidateStaffLoginResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Staff.ValidateStaffLoginResponse")
    public ValidateLoginResult validateStaffLogin(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        ValidateLoginRequest request);

}
