
package com.mindbodyonline.clients.api._0_5;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    com.mindbodyonline.clients.api._0_4.ObjectFactory.class,
    com.mindbodyonline.clients.api._0_5.ObjectFactory.class
})
public interface DataServiceSoap {


    /**
     * Issue a select statement to your MB database
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.SelectDataXmlResult
     */
    @WebMethod(operationName = "SelectDataXml", action = "http://clients.mindbodyonline.com/api/0_5/SelectDataXml")
    @WebResult(name = "SelectDataXmlResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "SelectDataXml", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SelectDataXml")
    @ResponseWrapper(localName = "SelectDataXmlResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SelectDataXmlResponse")
    public SelectDataXmlResult selectDataXml(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        SelectDataXmlRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.SelectDataXmlResult
     */
    @WebMethod(operationName = "FunctionDataXml", action = "http://clients.mindbodyonline.com/api/0_5/FunctionDataXml")
    @WebResult(name = "FunctionDataXmlResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "FunctionDataXml", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.FunctionDataXml")
    @ResponseWrapper(localName = "FunctionDataXmlResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.FunctionDataXmlResponse")
    public SelectDataXmlResult functionDataXml(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        FunctionDataXmlRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.SelectDataCSVResult
     */
    @WebMethod(operationName = "FunctionDataCSV", action = "http://clients.mindbodyonline.com/api/0_5/FunctionDataCSV")
    @WebResult(name = "FunctionDataCSVResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "FunctionDataCSV", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.FunctionDataCSV")
    @ResponseWrapper(localName = "FunctionDataCSVResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.FunctionDataCSVResponse")
    public SelectDataCSVResult functionDataCSV(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        FunctionDataXmlRequest request);

    /**
     * Issue a select statement to your MB database
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.SelectDataCSVResult
     */
    @WebMethod(operationName = "SelectDataCSV", action = "http://clients.mindbodyonline.com/api/0_5/SelectDataCSV")
    @WebResult(name = "SelectDataCSVResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "SelectDataCSV", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SelectDataCSV")
    @ResponseWrapper(localName = "SelectDataCSVResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SelectDataCSVResponse")
    public SelectDataCSVResult selectDataCSV(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        SelectDataCSVRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.SelectDataXmlResult
     */
    @WebMethod(operationName = "FunctionAggregateDataXml", action = "http://clients.mindbodyonline.com/api/0_5/FunctionAggregateDataXml")
    @WebResult(name = "FunctionAggregateDataXmlResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "FunctionAggregateDataXml", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.FunctionAggregateDataXml")
    @ResponseWrapper(localName = "FunctionAggregateDataXmlResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.FunctionAggregateDataXmlResponse")
    public SelectDataXmlResult functionAggregateDataXml(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        FunctionDataXmlRequest request);

    /**
     * Issue a select statement to aggregate data
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.SelectAggregateDataXmlResult
     */
    @WebMethod(operationName = "SelectAggregateDataXml", action = "http://clients.mindbodyonline.com/api/0_5/SelectAggregateDataXml")
    @WebResult(name = "SelectAggregateDataXmlResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "SelectAggregateDataXml", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SelectAggregateDataXml")
    @ResponseWrapper(localName = "SelectAggregateDataXmlResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SelectAggregateDataXmlResponse")
    public SelectAggregateDataXmlResult selectAggregateDataXml(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        SelectAggregateDataXmlRequest request);

    /**
     * Issue a select statement to aggregate data
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.SelectAggregateDataCSVResult
     */
    @WebMethod(operationName = "SelectAggregateDataCSV", action = "http://clients.mindbodyonline.com/api/0_5/SelectAggregateDataCSV")
    @WebResult(name = "SelectAggregateDataCSVResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "SelectAggregateDataCSV", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SelectAggregateDataCSV")
    @ResponseWrapper(localName = "SelectAggregateDataCSVResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SelectAggregateDataCSVResponse")
    public SelectAggregateDataCSVResult selectAggregateDataCSV(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        SelectAggregateDataCSVRequest request);

    /**
     * Retrieve all available FunctionData function names for a given sourcename.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetFunctionNamesResult
     */
    @WebMethod(operationName = "GetFunctionNames", action = "http://clients.mindbodyonline.com/api/0_5/GetFunctionNames")
    @WebResult(name = "GetFunctionNamesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetFunctionNames", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetFunctionNames")
    @ResponseWrapper(localName = "GetFunctionNamesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetFunctionNamesResponse")
    public GetFunctionNamesResult getFunctionNames(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetFunctionNamesRequest request);

    /**
     * Retrieve all available parameters for a given function.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetFunctionParametersResult
     */
    @WebMethod(operationName = "GetFunctionParameters", action = "http://clients.mindbodyonline.com/api/0_5/GetFunctionParameters")
    @WebResult(name = "GetFunctionParametersResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetFunctionParameters", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetFunctionParameters")
    @ResponseWrapper(localName = "GetFunctionParametersResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetFunctionParametersResponse")
    public GetFunctionParametersResult getFunctionParameters(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetFunctionParametersRequest request);

    /**
     * Retrieve all sites that you can access with FunctionData.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetSitesWithFunctionDataAccessResult
     */
    @WebMethod(operationName = "GetSitesWithFunctionDataAccess", action = "http://clients.mindbodyonline.com/api/0_5/GetSitesWithFunctionDataAccess")
    @WebResult(name = "GetSitesWithFunctionDataAccessResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetSitesWithFunctionDataAccess", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSitesWithFunctionDataAccess")
    @ResponseWrapper(localName = "GetSitesWithFunctionDataAccessResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSitesWithFunctionDataAccessResponse")
    public GetSitesWithFunctionDataAccessResult getSitesWithFunctionDataAccess(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetSitesWithFunctionDataAccessRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.RunFunctionForJobResult
     */
    @WebMethod(operationName = "RunFunctionForJob", action = "http://clients.mindbodyonline.com/api/0_5/RunFunctionForJob")
    @WebResult(name = "RunFunctionForJobResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "RunFunctionForJob", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.RunFunctionForJob")
    @ResponseWrapper(localName = "RunFunctionForJobResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.RunFunctionForJobResponse")
    public RunFunctionForJobResult runFunctionForJob(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        RunFunctionForJobRequest request);

}
