
package com.mindbodyonline.clients.api._0_5;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Site_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    com.mindbodyonline.clients.api._0_4.ObjectFactory.class,
    com.mindbodyonline.clients.api._0_5.ObjectFactory.class
})
public interface SiteX0020ServiceSoap {


    /**
     * Gets a list of sites.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetSitesResult
     */
    @WebMethod(operationName = "GetSites", action = "http://clients.mindbodyonline.com/api/0_5/GetSites")
    @WebResult(name = "GetSitesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetSites", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSites")
    @ResponseWrapper(localName = "GetSitesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSitesResponse")
    public GetSitesResult getSites(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetSitesRequest request);

    /**
     * Gets a list of locations.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetLocationsResult
     */
    @WebMethod(operationName = "GetLocations", action = "http://clients.mindbodyonline.com/api/0_5/GetLocations")
    @WebResult(name = "GetLocationsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetLocations", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetLocations")
    @ResponseWrapper(localName = "GetLocationsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetLocationsResponse")
    public GetLocationsResult getLocations(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetLocationsRequest request);

    /**
     * Gets an activation code.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetActivationCodeResult
     */
    @WebMethod(operationName = "GetActivationCode", action = "http://clients.mindbodyonline.com/api/0_5/GetActivationCode")
    @WebResult(name = "GetActivationCodeResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetActivationCode", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetActivationCode")
    @ResponseWrapper(localName = "GetActivationCodeResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetActivationCodeResponse")
    public GetActivationCodeResult getActivationCode(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetActivationCodeRequest request);

    /**
     * Gets a list of programs.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetProgramsResult
     */
    @WebMethod(operationName = "GetPrograms", action = "http://clients.mindbodyonline.com/api/0_5/GetPrograms")
    @WebResult(name = "GetProgramsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetPrograms", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetPrograms")
    @ResponseWrapper(localName = "GetProgramsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetProgramsResponse")
    public GetProgramsResult getPrograms(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetProgramsRequest request);

    /**
     * Gets a list of session types.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetSessionTypesResult
     */
    @WebMethod(operationName = "GetSessionTypes", action = "http://clients.mindbodyonline.com/api/0_5/GetSessionTypes")
    @WebResult(name = "GetSessionTypesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetSessionTypes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSessionTypes")
    @ResponseWrapper(localName = "GetSessionTypesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSessionTypesResponse")
    public GetSessionTypesResult getSessionTypes(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetSessionTypesRequest request);

    /**
     * Gets a list of resources.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetResourcesResult
     */
    @WebMethod(operationName = "GetResources", action = "http://clients.mindbodyonline.com/api/0_5/GetResources")
    @WebResult(name = "GetResourcesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetResources", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetResources")
    @ResponseWrapper(localName = "GetResourcesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetResourcesResponse")
    public GetResourcesResult getResources(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetResourcesRequest request);

    /**
     * Gets a list of relationships.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetRelationshipsResult
     */
    @WebMethod(operationName = "GetRelationships", action = "http://clients.mindbodyonline.com/api/0_5/GetRelationships")
    @WebResult(name = "GetRelationshipsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetRelationships", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetRelationships")
    @ResponseWrapper(localName = "GetRelationshipsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetRelationshipsResponse")
    public GetRelationshipsResult getRelationships(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetRelationshipsRequest request);

    /**
     * Gets all resources schedule.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetResourceScheduleResult
     */
    @WebMethod(operationName = "GetResourceSchedule", action = "http://clients.mindbodyonline.com/api/0_5/GetResourceSchedule")
    @WebResult(name = "GetResourceScheduleResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetResourceSchedule", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetResourceSchedule")
    @ResponseWrapper(localName = "GetResourceScheduleResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetResourceScheduleResponse")
    public GetResourceScheduleResult getResourceSchedule(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetResourceScheduleRequest request);

    /**
     * Reserves a resource.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.ReserveResourceResult
     */
    @WebMethod(operationName = "ReserveResource", action = "http://clients.mindbodyonline.com/api/0_5/ReserveResource")
    @WebResult(name = "ReserveResourceResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "ReserveResource", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.ReserveResource")
    @ResponseWrapper(localName = "ReserveResourceResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.ReserveResourceResponse")
    public ReserveResourceResult reserveResource(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        ReserveResourceRequest request);

}
