
package com.mindbodyonline.clients.api._0_5Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Client_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientX0020ServiceSoap {


    /**
     * Adds an arrival record for the given client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.AddArrivalResult
     */
    @WebMethod(operationName = "AddArrival", action = "http://clients.mindbodyonline.com/api/0_5/AddArrival")
    @WebResult(name = "AddArrivalResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddArrival", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.AddArrival")
    @ResponseWrapper(localName = "AddArrivalResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.AddArrivalResponse")
    public AddArrivalResult addArrival(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddArrivalRequest request);

    /**
     * Adds or updates information for a list of clients.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.AddOrUpdateClientsResult
     */
    @WebMethod(operationName = "AddOrUpdateClients", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateClients")
    @WebResult(name = "AddOrUpdateClientsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddOrUpdateClients", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.AddOrUpdateClients")
    @ResponseWrapper(localName = "AddOrUpdateClientsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.AddOrUpdateClientsResponse")
    public AddOrUpdateClientsResult addOrUpdateClients(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateClientsRequest request);

    /**
     * Gets a list of clients.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientsResult
     */
    @WebMethod(operationName = "GetClients", action = "http://clients.mindbodyonline.com/api/0_5/GetClients")
    @WebResult(name = "GetClientsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClients", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClients")
    @ResponseWrapper(localName = "GetClientsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientsResponse")
    public GetClientsResult getClients(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientsRequest request);

    /**
     * Gets a list of currently available client indexes.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetCustomClientFieldsResult
     */
    @WebMethod(operationName = "GetCustomClientFields", action = "http://clients.mindbodyonline.com/api/0_5/GetCustomClientFields")
    @WebResult(name = "GetCustomClientFieldsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetCustomClientFields", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetCustomClientFields")
    @ResponseWrapper(localName = "GetCustomClientFieldsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetCustomClientFieldsResponse")
    public GetCustomClientFieldsResult getCustomClientFields(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetCustomClientFieldsRequest request);

    /**
     * Gets a list of currently available client indexes.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientIndexesResult
     */
    @WebMethod(operationName = "GetClientIndexes", action = "http://clients.mindbodyonline.com/api/0_5/GetClientIndexes")
    @WebResult(name = "GetClientIndexesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientIndexes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientIndexes")
    @ResponseWrapper(localName = "GetClientIndexesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientIndexesResponse")
    public GetClientIndexesResult getClientIndexes(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientIndexesRequest request);

    /**
     * Get contact logs for a client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientContactLogsResult
     */
    @WebMethod(operationName = "GetClientContactLogs", action = "http://clients.mindbodyonline.com/api/0_5/GetClientContactLogs")
    @WebResult(name = "GetClientContactLogsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientContactLogs", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientContactLogs")
    @ResponseWrapper(localName = "GetClientContactLogsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientContactLogsResponse")
    public GetClientContactLogsResult getClientContactLogs(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientContactLogsRequest request);

    /**
     * Add or update client contact logs.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.AddOrUpdateContactLogsResult
     */
    @WebMethod(operationName = "AddOrUpdateContactLogs", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateContactLogs")
    @WebResult(name = "AddOrUpdateContactLogsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddOrUpdateContactLogs", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.AddOrUpdateContactLogs")
    @ResponseWrapper(localName = "AddOrUpdateContactLogsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.AddOrUpdateContactLogsResponse")
    public AddOrUpdateContactLogsResult addOrUpdateContactLogs(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateContactLogsRequest request);

    /**
     * Get contact log types for a client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetContactLogTypesResult
     */
    @WebMethod(operationName = "GetContactLogTypes", action = "http://clients.mindbodyonline.com/api/0_5/GetContactLogTypes")
    @WebResult(name = "GetContactLogTypesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetContactLogTypes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetContactLogTypes")
    @ResponseWrapper(localName = "GetContactLogTypesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetContactLogTypesResponse")
    public GetContactLogTypesResult getContactLogTypes(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetContactLogTypesRequest request);

    /**
     * Upload a client document.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.UploadClientDocumentResult
     */
    @WebMethod(operationName = "UploadClientDocument", action = "http://clients.mindbodyonline.com/api/0_5/UploadClientDocument")
    @WebResult(name = "UploadClientDocumentResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "UploadClientDocument", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.UploadClientDocument")
    @ResponseWrapper(localName = "UploadClientDocumentResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.UploadClientDocumentResponse")
    public UploadClientDocumentResult uploadClientDocument(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        UploadClientDocumentRequest request);

    /**
     * Gets a list of client formula notes.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientFormulaNotesResult
     */
    @WebMethod(operationName = "GetClientFormulaNotes", action = "http://clients.mindbodyonline.com/api/0_5/GetClientFormulaNotes")
    @WebResult(name = "GetClientFormulaNotesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientFormulaNotes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientFormulaNotes")
    @ResponseWrapper(localName = "GetClientFormulaNotesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientFormulaNotesResponse")
    public GetClientFormulaNotesResult getClientFormulaNotes(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientFormulaNotesRequest request);

    /**
     * Adds a formula note to a client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.AddClientFormulaNoteResult
     */
    @WebMethod(operationName = "AddClientFormulaNote", action = "http://clients.mindbodyonline.com/api/0_5/AddClientFormulaNote")
    @WebResult(name = "AddClientFormulaNoteResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddClientFormulaNote", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.AddClientFormulaNote")
    @ResponseWrapper(localName = "AddClientFormulaNoteResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.AddClientFormulaNoteResponse")
    public AddClientFormulaNoteResult addClientFormulaNote(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddClientFormulaNoteRequest request);

    /**
     * Deletes a formula note to a client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.DeleteClientFormulaNoteResult
     */
    @WebMethod(operationName = "DeleteClientFormulaNote", action = "http://clients.mindbodyonline.com/api/0_5/DeleteClientFormulaNote")
    @WebResult(name = "DeleteClientFormulaNoteResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "DeleteClientFormulaNote", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.DeleteClientFormulaNote")
    @ResponseWrapper(localName = "DeleteClientFormulaNoteResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.DeleteClientFormulaNoteResponse")
    public DeleteClientFormulaNoteResult deleteClientFormulaNote(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        DeleteCientFormulaNoteRequest request);

    /**
     * Gets a list of clients.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientReferralTypesResult
     */
    @WebMethod(operationName = "GetClientReferralTypes", action = "http://clients.mindbodyonline.com/api/0_5/GetClientReferralTypes")
    @WebResult(name = "GetClientReferralTypesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientReferralTypes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientReferralTypes")
    @ResponseWrapper(localName = "GetClientReferralTypesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientReferralTypesResponse")
    public GetClientReferralTypesResult getClientReferralTypes(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientReferralTypesRequest request);

    /**
     * Gets the active membership for a given client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetActiveClientMembershipsResult
     */
    @WebMethod(operationName = "GetActiveClientMemberships", action = "http://clients.mindbodyonline.com/api/0_5/GetActiveClientMemberships")
    @WebResult(name = "GetActiveClientMembershipsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetActiveClientMemberships", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetActiveClientMemberships")
    @ResponseWrapper(localName = "GetActiveClientMembershipsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetActiveClientMembershipsResponse")
    public GetActiveClientMembershipsResult getActiveClientMemberships(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetActiveClientMembershipsRequest request);

    /**
     * Gets a list of contracts for a given client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientContractsResult
     */
    @WebMethod(operationName = "GetClientContracts", action = "http://clients.mindbodyonline.com/api/0_5/GetClientContracts")
    @WebResult(name = "GetClientContractsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientContracts", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientContracts")
    @ResponseWrapper(localName = "GetClientContractsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientContractsResponse")
    public GetClientContractsResult getClientContracts(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientContractsRequest request);

    /**
     * Gets account balances for the given clients.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientAccountBalancesResult
     */
    @WebMethod(operationName = "GetClientAccountBalances", action = "http://clients.mindbodyonline.com/api/0_5/GetClientAccountBalances")
    @WebResult(name = "GetClientAccountBalancesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientAccountBalances", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientAccountBalances")
    @ResponseWrapper(localName = "GetClientAccountBalancesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientAccountBalancesResponse")
    public GetClientAccountBalancesResult getClientAccountBalances(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientAccountBalancesRequest request);

    /**
     * Gets a client service for a given client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientServicesResult
     */
    @WebMethod(operationName = "GetClientServices", action = "http://clients.mindbodyonline.com/api/0_5/GetClientServices")
    @WebResult(name = "GetClientServicesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientServices", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientServices")
    @ResponseWrapper(localName = "GetClientServicesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientServicesResponse")
    public GetClientServicesResult getClientServices(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientServicesRequest request);

    /**
     * Get visits for a client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientVisitsResult
     */
    @WebMethod(operationName = "GetClientVisits", action = "http://clients.mindbodyonline.com/api/0_5/GetClientVisits")
    @WebResult(name = "GetClientVisitsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientVisits", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientVisits")
    @ResponseWrapper(localName = "GetClientVisitsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientVisitsResponse")
    public GetClientVisitsResult getClientVisits(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientVisitsRequest request);

    /**
     * Get purchases for a client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientPurchasesResult
     */
    @WebMethod(operationName = "GetClientPurchases", action = "http://clients.mindbodyonline.com/api/0_5/GetClientPurchases")
    @WebResult(name = "GetClientPurchasesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientPurchases", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientPurchases")
    @ResponseWrapper(localName = "GetClientPurchasesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientPurchasesResponse")
    public GetClientPurchasesResult getClientPurchases(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientPurchasesRequest request);

    /**
     * Get visits for a client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetClientScheduleResult
     */
    @WebMethod(operationName = "GetClientSchedule", action = "http://clients.mindbodyonline.com/api/0_5/GetClientSchedule")
    @WebResult(name = "GetClientScheduleResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClientSchedule", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientSchedule")
    @ResponseWrapper(localName = "GetClientScheduleResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetClientScheduleResponse")
    public GetClientScheduleResult getClientSchedule(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientScheduleRequest request);

    /**
     * Updates a client service for a given client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.GetRequiredClientFieldsResult
     */
    @WebMethod(operationName = "GetRequiredClientFields", action = "http://clients.mindbodyonline.com/api/0_5/GetRequiredClientFields")
    @WebResult(name = "GetRequiredClientFieldsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetRequiredClientFields", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetRequiredClientFields")
    @ResponseWrapper(localName = "GetRequiredClientFieldsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.GetRequiredClientFieldsResponse")
    public GetRequiredClientFieldsResult getRequiredClientFields(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetRequiredClientFieldsRequest request);

    /**
     * Validates a username and password. This method returns the associated clients record and a session guid on success.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.ValidateLoginResult
     */
    @WebMethod(operationName = "ValidateLogin", action = "http://clients.mindbodyonline.com/api/0_5/ValidateLogin")
    @WebResult(name = "ValidateLoginResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "ValidateLogin", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.ValidateLogin")
    @ResponseWrapper(localName = "ValidateLoginResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.ValidateLoginResponse")
    public ValidateLoginResult validateLogin(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        ValidateLoginRequest request);

    /**
     * Updates a client service for a given client.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.UpdateClientServicesResult
     */
    @WebMethod(operationName = "UpdateClientServices", action = "http://clients.mindbodyonline.com/api/0_5/UpdateClientServices")
    @WebResult(name = "UpdateClientServicesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "UpdateClientServices", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.UpdateClientServices")
    @ResponseWrapper(localName = "UpdateClientServicesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.UpdateClientServicesResponse")
    public UpdateClientServicesResult updateClientServices(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        UpdateClientServicesRequest request);

    /**
     * Sends the user a new password.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5Client.ClientSendUserNewPasswordResult
     */
    @WebMethod(operationName = "SendUserNewPassword", action = "http://clients.mindbodyonline.com/api/0_5/SendUserNewPassword")
    @WebResult(name = "SendUserNewPasswordResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "SendUserNewPassword", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.SendUserNewPassword")
    @ResponseWrapper(localName = "SendUserNewPasswordResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5Client.SendUserNewPasswordResponse")
    public ClientSendUserNewPasswordResult sendUserNewPassword(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        ClientSendUserNewPasswordRequest request);

}
